src: fix build with musl libc
The GNU version of 'struct tcphdr' is not exposed by musl libc headers
unless _GNU_SOURCE is defined. Without this definition, the build fails
with:

  rpc.c: In function 'rpc_helper_cb':
  rpc.c:351:15: error: 'struct tcphdr' has no member named 'doff'
     offset += th->doff * 4;
                 ^

Signed-off-by: Rodrigo Rebello <rprebello@gmail.com>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>